application/routes/about.py
from flask import Blueprint, request, render_template, redirect, url_for
from data import people_info

about_bp = Blueprint('about', __name__)

@about_bp.route('/About Me')
def team():
    names = list(people_info.keys())
    return render_template('index.html', names=names)

@about_bp.route('/about/<name>')
def about(name):
    person = people_info.get(name)
    if person:
        return render_template('about.html', person=person)
    else:
        return "Person not found"

@about_bp.route('/about/<name>/update', methods=['POST'])
def update_about(name):
    if request.method == 'POST':
        about = request.form['about']
        person = people_info.get(name)
        if person:
            person['about'] = about
            return redirect(url_for('about.about', name=name))
        else:
            return "Person not found"
    else:
        return redirect(url_for('about.about', name=name))

application/routes/landing.py
from flask import Blueprint, render_template

landing_bp = Blueprint('landing', __name__)

@landing_bp.route('/')
def landing():
    return render_template('landing.html')

application/routes/login.py
from flask import Blueprint, request, render_template, redirect, url_for, session,flash
import MySQLdb.cursors
import bcrypt
from extensions import mysql
import base64

login_bp = Blueprint('login', __name__)

@login_bp.route('/login', methods=['GET', 'POST'])
def login():
    msg = None  # Initialize msg
    if request.method == 'POST' and 'email' in request.form and 'password' in request.form:
        email = request.form['email']
        password = request.form['password']

        cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM Users WHERE email = %s', (email,))
        user = cursor.fetchone()
        cursor.close()

        if user and bcrypt.checkpw(password.encode('utf-8'), user['password'].encode('utf-8')):
            session['loggedin'] = True
            session['email'] = user['email']
            session['firstname'] = user['firstName']
            session['lastname'] = user['lastName']
            session['user_id'] = user['user_id']  
            if '@example' in user['email']:
                session['is_admin'] = True
            else:
                session['is_admin'] = False
            return redirect(url_for('login.loggedlanding', user_id=user['user_id'], full_name=user['fullName']))
        else:
            flash('Incorrect email/password!', 'error')  # Set a flash message

            msg = 'Incorrect email/password!'
    
    return render_template('login.html', msg=msg, session=session)

@login_bp.route('/unilogin', methods=['GET', 'POST'])
def unilogin():
    msg = None  # Initialize msg
    if request.method == 'POST' and 'email' in request.form and 'password' in request.form:
        email = request.form['email']
        password = request.form['password']

        cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM Universities WHERE email = %s', (email,))
        university = cursor.fetchone()
        cursor.close()

        if university and password == university['password']:
            session['loggedin'] = True
            session['email'] = university['email']
            session['university_id'] = university['university_id']
            session['uni_name'] = university['uni_name']
            if '@example' in university['email']:
                session['is_admin'] = True
            else:
                session['is_admin'] = False

            return redirect(url_for('login.uniloggedlanding', university_id=university['university_id'], uni_name=university['uni_name']))
        else:
            flash('Incorrect email/password!', 'error')  # Set a flash message

            msg = 'Incorrect email/password!'
    
    return render_template('unilogin.html', msg=msg)

@login_bp.route('/loggedlanding')
def loggedlanding():
    user_id = request.args.get('user_id')
    full_name = request.args.get('full_name')

    cursor = mysql.connection.cursor()
    cursor.execute("SELECT file_data FROM UserProfileImg WHERE user_id = %s ORDER BY uploaded_at DESC LIMIT 1", [user_id])
    result = cursor.fetchone()
    cursor.close()

    profile_picture = None
    if result:
        profile_picture = base64.b64encode(result[0]).decode('utf-8')

    return render_template('loggedlanding.html', user_id=user_id, full_name=full_name, profile_picture=profile_picture)

@login_bp.route('/universityHome')
def uniloggedlanding():
    uni_name = request.args.get('uni_name')

    cursor = mysql.connection.cursor()
    cursor.execute("SELECT address, city, state, zipcode, email, phone FROM Universities WHERE uni_name = %s", (uni_name,))
    result = cursor.fetchone()
    cursor.close()

    if result:
        address, city, state, zipcode, email, phone_number = result
        formatted_address = f"{address}, {city}, {state} {zipcode}"
        API_KEY = 'AIzaSyByc-Nkq0OG7uysLeAzABMVjnPQpOeU1IU'
        return render_template('universityHome.html', uni_name=uni_name, address=formatted_address, api_key=API_KEY, email=email, phone=phone_number)
    else:
        return "University not found"

application/routes/register.py
from flask import Blueprint, request, render_template, redirect, url_for
import MySQLdb.cursors
import re
import bcrypt
from extensions import mysql

register_bp = Blueprint('register', __name__)

@register_bp.route('/register', methods=['GET', 'POST'])
def register():
    msg = None  # Initialize msg
    if request.method == 'POST' and 'firstName' in request.form and 'lastName' in request.form and 'email' in request.form and 'password' in request.form:
        firstName = request.form.get('firstName')
        lastName = request.form.get('lastName')
        email = request.form.get('email')
        password = request.form.get('password')

        # Check if the email already exists in the database
        cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM Users WHERE email = %s ', (email,))
        user = cursor.fetchone()

        if user:
            # If user with the same email already exists
            msg = 'An account with this email already exists.'
        elif not firstName or not lastName or not email or not password:
            msg = 'Please fill out all fields.'
        elif not re.match(r'^[A-Za-z0-9]+$', firstName):
            msg = 'Username must contain only letters and numbers.'
        elif not re.match(r'^[A-Za-z0-9]+$', lastName):
            msg = 'Username must contain only letters and numbers.'
        elif not re.match(r'[^@]+@[^@]+\.[^@]+', email):
            msg = 'Invalid email address.'
        else:
            hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())
            # If the email is not already registered, proceed with registration
            cursor.execute("INSERT INTO Users (email, password, firstName, lastName) VALUES (%s, %s, %s, %s)", (email, hashed_password, firstName, lastName))
            mysql.connection.commit()
            msg = 'User registered successfully!'
            return redirect(url_for('login.login', msg=msg))  # Redirect to login page after successful registration

        cursor.close()

    return render_template('register.html', msg=msg)

@register_bp.route('/uniregister', methods=['GET', 'POST'])
def uniregister():
    msg = None  # Initialize msg
    if request.method == 'POST' and 'uni_name' in request.form and 'email' in request.form and 'password' in request.form:
        uni_name = request.form.get('uni_name')
        email = request.form.get('email')
        password = request.form.get('password')
        phone = request.form.get('phone')
        address = request.form.get('address')
        city = request.form.get('city')
        state = request.form.get('state')
        zipcode = request.form.get('zipcode')
        country = request.form.get('country')

        try:
            # Check if the email already exists in the database
            cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
            cursor.execute('SELECT * FROM Universities WHERE email = %s ', (email,))
            university = cursor.fetchone()

            if university: 
                # If university with the same email already exists
                msg = 'An account with this email already exists.'
            elif not uni_name or not email or not password or not phone or not address or not city or not state or not zipcode or not country:
                msg = 'Please fill out all fields.'
            elif not re.match(r'[^@]+@[^@]+\.[^@]+', email):
                msg = 'Invalid email address.'
            else:
                print("i am here ")
                # If the email is not already registered, proceed with registration
                cursor.execute("INSERT INTO Universities (email, uni_name, password, phone, address, city, state, zipcode, country) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)", (email, uni_name, password, phone, address, city, state, zipcode, country))
                mysql.connection.commit()
                msg = 'University registered successfully!'
                return redirect(url_for('login.unilogin', msg=msg))  # Redirect to login page after successful registration

        except Exception as e:
            # Handle database errors
            msg = f"Error: {e}"

        finally:
            if 'cursor' in locals():
                cursor.close()

    return render_template('uniregister.html', msg=msg)

application/templates/partials/banner.html
    <!-- Banner -->
    <div class="banner-container">
        <div class="banner-container">
            <p class="banner-text">SFSU Software Engineering Project CSC 648-848, Spring 2024 | For Demonstration Only | Section 2 Team 05</p>
        </div>
    </div>

application/templates/partials/navbar.html
<!-- templates/partials/_navbar.html -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a href="{{ url_for('landing.landing') }}" class="navbar-brand">
        <img src="{{ url_for('static', filename='css/OlymPick-logo.jpg') }}" width="30" height="30" alt="OlymPick Logo">
        OlymPick
    </a>

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto"> <!-- ml-auto to align the menu items to the right -->
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('landing.landing') }}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('about.team') }}">About</a>
            </li>
            {% if 'loggedin' in session and session.get('user_id') and session.get('full_name') %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('profile.profile', user_id=session.get('user_id')) }}">My Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('login.logout') }}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="btn btn-primary" href="{{ url_for('login.login') }}" role="button">Login</a> 
                <a class="btn btn-primary" href="{{ url_for('login.unilogin') }}">University Login</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-outline-primary" href="{{ url_for('register.register') }}" role="button">Register</a> 
                <a  class="btn btn-outline-primary" href="{{ url_for('register.uniregister') }}">University Register</a>

            </li>
            {% endif %}
        </ul>
    </div>
</nav>

application/templates/partials/searchbar.html
<!-- searchbar.html -->
<div class="search-container">
    <form action="/search" method="post" class="search-bar">
        <input type="text" name="searchTerm" id="search-input" placeholder="Search...">
        <select name="searchFilter" class="search-select">
            <option value="University">University</option>
            <option value="Sports">Sports</option>
            <option value="State">State</option>
        </select>
        <button type="submit" class="search-button">Search</button>
    </form>
</div>

<!-- JavaScript for filter options -->
<script>
    document.addEventListener("DOMContentLoaded", function () {
        var filterOptions = document.querySelectorAll('.search-select option');
        var searchInput = document.getElementById('search-input');

        filterOptions.forEach(function (option) {
            option.addEventListener('click', function (event) {
                event.preventDefault();
                var placeholderText = "Searching " + this.value + "...";
                searchInput.setAttribute('placeholder', placeholderText);
            });
        });
    });
</script>

application/templates/partials/universityHeader.html
<div class="header">
    <div class="container">
        <div class="row">
            <div class="col-md">
                <div class="card bg-secondary">
                    <div class="card-body">
                        <a href="{{ url_for('universityPage.home', uni_name=uni_name) }}" class="card-link text-white">Home</a>
                    </div>
                </div>
            </div>
            <div class="col-md">
                <div class="card bg-primary">
                    <div class="card-body">
                        <a href="{{ url_for('universityPage.sports', uni_name=uni_name) }}" class="card-link text-white">Sports</a>
                    </div>
                </div>
            </div>
            <div class="col-md">
                <div class="card bg-primary">
                    <div class="card-body">
                        <a href="{{ url_for('universityPage.athletes', uni_name=uni_name) }}" class="card-link text-white">Athletes</a>
                    </div>
                </div>
            </div>
            <div class="col-md">
                <div class="card bg-primary">
                    <div class="card-body">
                        <a href="{{ url_for('universityPage.faculty', uni_name=uni_name) }}" class="card-link text-white">Faculty</a>
                    </div>
                </div>
            </div>
            <div class="col-md">
                <div class="card bg-primary">
                    <div class="card-body">
                        <a href="{{ url_for('universityPage.contact', uni_name=uni_name) }}" class="card-link text-white">Contact Us</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>